### ISSUE TITLE
How to use the samples?

### ISSUE THREAD

**Issue by laultman** [microsoft/OpenXR-Unity-MixedReality-Samples#111]
Would somebody please tell us how to import, copy, drag-drop- whatever to use this stuff? Got an empty project created following these instructions [here](https://learn.microsoft.com/en-us/windows/mixed-reality/develop/unity/new-openxr-project-with-mrtk). It links to here this repo.
My brand new supposedly MRTK ready project has a SampleScene just like it looked when Unity created the project. Obviously some steps are missing between setup and actually using MRTK or any sample.

**Comment by laultman** [comment]
Just in case there is somebody else out there looking, I found the missing steps - not in any links mind you but  here you go...

In the Mixed Reality documentation section:
Locate Unity/Tutorials/HoloLens2 Fundamentals Tutorials
Step your way through until you find setp 5 - import and configure. Scroll to near the bottom and look for "Create the scene and configure MRTK".
These instructions tell you how to actually hook MRTK to a Unity project.
It you be much easier to provide this in the documentation instead of a Tutorial. I like the tutorial but that is a bad place to put critical setup information.

**Comment by laultman** [comment]
By the way I still don't know how to use the samples!

**Comment by keveleigh** [comment]
The tutorial you linked to is about getting started fresh, not about using these samples. The link to this repo is an additional resource for learning how to do more with OpenXR in Unity.

If you're looking to try these samples, each of the three folders that end in the word "Sample" are themselves distinct Unity projects and can be opened directly in Unity once you've cloned this repo.

**Comment by laultman** [comment]
@keveleigh Thank you Kurtis you most helpful comment. I thought it was clear that I was starting fresh, perhaps you skimmed the comments rather that read them. 
Maybe I could state it more succinctly for you, the documentation is scattered across multiple pages that a person starting fresh is unable to discern how to get even the most basic MRTK project working in Unity without hours of frustration. It turns out that the Tutorial has the best combination of documentation about how to get started with MRTK in Unity. The Tutorial stops short of how to use a sample - as this is not the Tutorial's intent.
Thankfully someone did read and respond with the answer on another thread [here ](https://github.com/microsoft/MixedReality-WorldLockingTools-Unity/issues/308) for anyone else looking.

**Comment by keveleigh** [comment]
The other response is about the WLT samples, which are not the same as the samples in **this** repo you commented on. You didn't mention WLT in this post, so I'm not sure there was anything for me to skim! I'm happy to help you get these samples working, but you don't seem to want my help.

In the future, it would be good if you commented more clearly the problems you're hitting and what you're trying to get working instead of just generally saying "everything is wrong and the samples don't work". Those types of comments don't provide enough info and aren't helpful for debugging or providing advice.

Neither this repo nor WLT is specific to MRTK either, but you keep mentioning MRTK so I can try to help you there: if you want MRTK2's examples from the installed packages, the steps are at https://learn.microsoft.com/windows/mixed-reality/mrtk-unity/mrtk2/running-example-scenes. If you just want to know how to get started with MRTK2, you can try the tutorial series at https://learn.microsoft.com/training/paths/beginner-hololens-2-tutorials.

I'm going to go ahead and lock the various threads you've started across the repos, as you say you've been helped, and the tone of the responses is starting to fall outside one conducive to a helpful and collaborative community. Thanks for your contributions.

Kurtis

**Comment by keveleigh** [comment]
Here's a link to the Microsoft Code of Conduct that governs all our repos, for future reference: https://opensource.microsoft.com/codeofconduct/
