### ISSUE TITLE
Build for iOS with compiling error, SpatialAnchorsSample.cs

### ISSUE THREAD

**Issue by ttkrpink** [microsoft/OpenXR-Unity-MixedReality-Samples#37]
ASA 2.10.1
MRTK 2.7.2
Unity 20.21.1.15fc1
AR Foundation 4.1.7
ARKit Plugin 4.1.7
Mixed Reality OpenXR Plugin 1.0.1
OpenXR Plugin 1.2.3

Build for Hololens without any problem. When I switch to iOS, SpatialAnchorsSample.cs has compiling errors.
Assets\Scripts\SpatialAnchorsSample.cs(33,19): error CS0246: The type or namespace name 'CloudSpatialAnchorWatcher' could not be found (are you missing a using directive or an assembly reference?)
Assets\Scripts\SpatialAnchorsSample.cs(101,71): error CS0246: The type or namespace name 'AnchorLocatedEventArgs' could not be found (are you missing a using directive or an assembly reference?)

And m_spatialAnchorManager does not have AnchorLocated nor LocateAnchorsCompleted delegate. I guess the delegate problem is related to the namespace problem.

**Comment by yl-msft** [comment]
@ttkrpink  Thanks for the report.   I suppose you've added the ASA ios package to this project:

![image](https://user-images.githubusercontent.com/33265158/126567883-f58d23e3-7e1f-4ad6-b62d-d05f3ce8d358.png)

In addition to this, you also need to add this line in the main sample's asmdef assembly reference, so that you can use the type defined in the ios assembly:

![image](https://user-images.githubusercontent.com/33265158/126567968-fb7f7550-8810-4e4a-9ea2-f838fb6d3672.png)

Let us know if this helps, or you need anything more here.

**Comment by ttkrpink** [comment]
Thanks for your help. I add iOS runtime in the Assembly Definition Asset. Play mode has no error (at least Unity does not complain about C# code). When I start to build, ASA core starts to complain. 

![image](https://user-images.githubusercontent.com/2522889/126610415-9fb7a434-8e58-4a10-8a8e-55cfb5b534f9.png)

Let me know if you need further information

**Comment by ttkrpink** [comment]
So, with the Windows XR Plugin deprecated in 2021.2, I am switching everything to OpenXR. Since the iOS can't be built with the above error, I tried Android. Unfortunately, the same error message pops up.

So, is there a way to share experience across platforms?

**Comment by yl-msft** [comment]
@ttkrpink  we are working with the ASA team for a solution on this.  It takes sometime, thanks for your patience.
