### ISSUE TITLE
"com.microsoft.mixedreality.openxr-1.0.3.tgz is not a valid package tarball"

### ISSUE THREAD

**Issue by nicolashahn** [microsoft/OpenXR-Unity-MixedReality-Samples#45]
I'm seeing this error when attempting to start the BasicSample project. On Windows, using Unity 2020.3.15f2. Any idea why this is happening?

**Comment by keveleigh** [comment]
I believe we use git LFS for the tarballs in this repo. https://git-lfs.github.com/
You may need to enable that specifically for this repo in order to ensure the .tgz files are pulled down. You can check if this is the case by looking in the MixedRealityPackages folder and seeing if you see actual .tgz files or placeholders.

**Comment by yl-msft** [comment]
@nicolashahn hope you have solved this by enabling git LFS before cloning the repo.  This is a common mistaken developer make for unity git repo.  Let us know if you have further questions.
