### ISSUE TITLE
Locatable Camera

### ISSUE THREAD

**Issue by aakashres** [microsoft/OpenXR-Unity-MixedReality-Samples#71]
How to pin point the position of any hologram present in camera frame while capturing image from locatable camera?

**Comment by yl-msft** [comment]
@aakashres ,  could you please elaborate what do you mean by "pin point the position"?

**Comment by yl-msft** [comment]
@aakashres ,  Since we've not received further clarification, we will resolve this issue.

I can only speculate the intention from your original message:

If you mean "locate the hologram in the locatable camera's image", because the app renders the hologram in Unity, you should have the 3D location of the hologram.  Then to locate the hologram in locatable camera, you will need to project the 3D location to the MRC frame using projection matrix provided from the locatable camera.   [This sample showed a way to obtain this project matrix from Unity's API. ](https://github.com/microsoft/OpenXR-Unity-MixedReality-Samples/blob/main/BasicSample/Assets/LocatableCamera/Scripts/LocatableCamera.cs#L145)
