### ISSUE TITLE
Spatial graph nodes

### ISSUE THREAD

**Issue by sjando** [microsoft/OpenXR-Unity-MixedReality-Samples#72]
The latest plugin release (1.4.0) exposes the ability to work with dynamic spatial graph nodes, specifically calling out interop with PV camera tracking. Hopefully this is an OK place to ask but I have a number of questions about this and about the 'spatial graph' concept in general. So far I've encountered HL2 spatial graph nodes coming from a few different places:

- Mixed Reality QR library (static)
- Research Mode API (dynamic)
- Node IDs listed against spatial anchors in Map Manager in HL2 device portal (static)
- SpatialGraphInteropFrameOfReferencePreview objects created from SpatialCoordinateSystem objects (static)

My questions are:

- Are the other APIs which are sources of spatial graph nodes? How can they be created? I have seen no API for creating them, only for interacting with existing GUIDs.
- What is the difference between dynamic and static nodes? Static nodes appear to move/adjust over time as dynamic ones do.
- What is the difference between spatial graph nodes and SpatialCoordinateSystem? Are these two things equivalent? Why do some APIs seem to expose only one or the other?
- How do spatial anchors relate to spatial graph nodes? One node often seems to map to many anchors (see Map Manager). Is a persisted spatial anchor anything more than a record of a spatial node GUID plus an offset?
- How does one obtain a dynamic node representing the PV camera (as hinted at in 1.4.0 release notes)? I've previously used _SpatialGraphInteropFrameOfReferencePreview_ + _MediaFrameReference_.CoordinateSystem + _XR_MSFT_spatial_graph_bridge_ to obtain PV camera poses when using OpenXR. But a dynamic node sounds cleaner/better.
- SpatialGraphInteropFrameOfReferencePreview and its peers have been "preview" for a long time. Is this stuff safe/reliable to use and will it ever be considered "not preview". Why do they exist at all, could every Windows API not just directly expose a node GUID which maps much more cleanly to OpenXR?

I would love to simplify much of my Unity code and track all these different things (anchors, QR codes, PV camera, research mode sensors etc) in a consistent manner using the SpatialGraphNode functionality in this plugin (especially now that it supports dynamic nodes) but my understanding of how everything fits together is still a bit hazy.

**Comment by yl-msft** [comment]
@sjando  these are great questions.  SpatialGraph node is an important way for the OpenXR API (mostly for XR rendering, tracking and inputs) to interop and collaborate with other parts of the system or devices on HL2.

You've got a pretty good summary yourself, probably better than our documentation so far.  Let me try to answer your questions to see if I can help on some clarity here.

1.  Are there other APIs to create spatial graph nodes?   
At this moment, we are focusing enabling the interop with existing libraries on HL2 such as PV camera from media foundation, or QR code, SU SDK etc.  You've listed more sources of the node id than I know :)  These different sources of the node Id are consistent in there capability of providing tracking inputs, but each of them provide different additional information in their specific area.
2. What's the difference between dynamic and static node?   
A "StaticNode" represent a tracked point in the stationary frame of reference, that has no measurable acceleration with the world around the user.  Their tracking inputs might still be moved when our tracking system adjusted but their movement are not sensitive to motions, and mostly adjustments with latest information, for example when QR code is moved to a new location and our camera discovered the visual is at a new place.
On the other hand, the "DynamicNode" represent a tracked point moving in the space, such as the PV camera on the HL2 device.  Their pose inputs are continuous and sensitive to the time at which the app is querying the location.
3. What is relationship between "SpatialCoordinateSystem" and "SpatialGraphNode"?
The "SpatialCoordinateSystem" is a concept on WinRT HoloLens APIs, it's the same as the XrSpace handle in OpenXR API.  It represents the abstraction of a tracked point and its lifecycle represents the resources in the platform to track the point.  The "SpatialCoordinateSystem" on WinRT are used in pairs to locate between coordinate system.  The XrSpace handle on OpenXR are the same.  In Unity, most of such "location between spaces" are exposed in API as "location relative to Unity's scene origin".
The "SpatialGraphNode" on the other hand, is not directly used to locate between spaces,  they represent the tracking resource in the driver that can be converted into a XrSpace to locate with other spaces.  When using OpenXR plugin, the [SpatialGraphNode class](https://docs.microsoft.com/dotnet/api/microsoft.mixedreality.openxr.spatialgraphnode) is to convert a SpatialGraphNode into a XrSpace that can provide location of it relative to the Unity's scene origin.
4. How do spatial anchor relate to spatial graph nodes?
"spatial anchor", both the one in WinRT "SpatialAnchor" and the one in openxr "XrSpatialAnchor" handle, are representing the tracking of an app specified location in the stationary world.  However, the "SpatialGraphNode" represents a location the tracking system is tracking, and that's why app cannot create arbitrary "spatial graph node".
5. How does one obtain a dynamic node representing the PV camera on HL2?
You will need need to use MediaCapture API to get the [MFSampleExtension_CameraExtrinsics](https://docs.microsoft.com/en-us/windows/win32/medfound/mfsampleextension-cameraextrinsics) and use the GUID output from this attribute as dynamic node.  You can find some winrt samples [here ](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/native/locatable-camera-cpp#using-media-foundation).  We don't have openxr sample or Unity sample for this yet.
6. The winrt preview APIs related to spatial graph node
The OpenXR apis are replacement of these preview APIs.  We intent to make the Unity plugin's SpatialGraphNode class to be useful to interop with these GUID concepts in other libraries on HL2 to provide tracking inputs, either dynamic or static nodes.  Let us know if this [SpatialGraphNode class ](https://docs.microsoft.com/dotnet/api/microsoft.mixedreality.openxr.spatialgraphnode) is enough for you, and let us know if you need something else that you have to look back at the preview APIs.  We can help.

**Comment by sjando** [comment]
Thanks for the detailed response!
